### ISSUE TITLE
Installation on arm / Mac OS? 

### ISSUE THREAD

**Issue by mat-ej** [slacgismo/solar-data-tools#150]
Hi slacgismo team, 

I am looking forward to trying your tool. However I seem to be unable to install it properly on Mac OS hardware. 

I do have poetry for project environment 
`pip install -e . `

inside solar-data-tools project directory fails with: 

```
     104 | #   error <cstdio> tried including <stdio.h> but didn't find libc++'s <stdio.h> header. \
                  |     ^
            fatal error: too many errors emitted, stopping now [-ferror-limit=]
            193 warnings and 20 errors generated.
            error: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
      Failed to build qdldl
      ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
      [end of output]

```
I brew install everything required I believe, cmake, openblas everything, set up the paths and then try pip install from source 

`pip install --no-binary :all: solar-data-tools`

this fails as well.

Have you perhaps found a routine to install solar-data-tools completely on mac os arm ? 

EDIT: here's my setup
Mac M2

```
(solar-data-tools) repo/solar-data-tools » pkg-config --libs --cflags  openblas
-I/opt/homebrew/Cellar/openblas/0.3.27/include -L/opt/homebrew/Cellar/openblas/0.3.27/lib -lopenblas
```
```
(solar-data-tools) repo/solar-data-tools » pkg-config --modversion openblas    
0.3.27
```

EDIT:
**The process seem to fail on installing osqp**

So I tried 
`pip install --no-binary :all: "osqp>=0.6.2"`

and this surprisingly fails on building numpy.

```
ERROR: Failed building wheel for numpy
            Failed to build numpy
```

Thanks and have a great weekend. : )

**Comment by bmeyers** [comment]
Hi @mat-ej, sorry to hear about your issues. I did want to check first, are you intentionally installing in editable mode to change the codebase? If not, I'd recommend a simple `pip install solar-data-tools` in a fresh virtual environment (Python 3.10 or earlier).

I just did a test on my Mac M2 and did not run into any problems building qdldl when installing solar data tools in editable mode. I started with a fresh Python 3.12.3 virtual environment with the following packages:

```  bzip2              pkgs/main/osx-arm64::bzip2-1.0.8-h80987f9_6 
  ca-certificates    pkgs/main/osx-arm64::ca-certificates-2024.3.11-hca03da5_0 
  expat              pkgs/main/osx-arm64::expat-2.6.2-h313beb8_0 
  libcxx             pkgs/main/osx-arm64::libcxx-14.0.6-h848a8c0_0 
  libffi             pkgs/main/osx-arm64::libffi-3.4.4-hca03da5_1 
  ncurses            pkgs/main/osx-arm64::ncurses-6.4-h313beb8_0 
  openssl            pkgs/main/osx-arm64::openssl-3.0.13-h1a28f6b_1 
  pip                pkgs/main/osx-arm64::pip-23.3.1-py312hca03da5_0 
  python             pkgs/main/osx-arm64::python-3.12.3-h99e199e_0 
  readline           pkgs/main/osx-arm64::readline-8.2-h1a28f6b_0 
  setuptools         pkgs/main/osx-arm64::setuptools-68.2.2-py312hca03da5_0 
  sqlite             pkgs/main/osx-arm64::sqlite-3.45.3-h80987f9_0 
  tk                 pkgs/main/osx-arm64::tk-8.6.12-hb8d0fd4_0 
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0 
  wheel              pkgs/main/osx-arm64::wheel-0.43.0-py312hca03da5_0 
  xz                 pkgs/main/osx-arm64::xz-5.4.6-h80987f9_1 
  zlib               pkgs/main/osx-arm64::zlib-1.2.13-h18a0788_1 
```

Then I ran `pip install -e .` in the top level of the main branch of SDT. This successfully built qdldl:

```
Building wheel for qdldl (pyproject.toml) ... done
  Created wheel for qdldl: filename=qdldl-0.1.7.post2-cp312-cp312-macosx_11_0_arm64.whl size=92431 sha256=c308172ce7221be69f51e9e847a4a2b6d78864876ec1543625a4c7a27158e04a
  Stored in directory: /Users/bennetm/Library/Caches/pip/wheels/fc/d5/cf/99fb9f55ba58b0b213d5b2581176a177417ac24a2f2e6b9785
Successfully built solar-data-tools qdldl
```

I know building qdldl has caused some problems for the community for a while ([1](https://stackoverflow.com/questions/65920955/failed-building-wheel-for-qdldl-when-installing-cvxpy), [2](https://github.com/osqp/osqp/issues/599)), but in my experience, it typically comes down to an issue with `cmake`. You might try reinstalling cmake with homebrew and see if that fixes it. Otherwise, I might recommend trying to build things in Python 3.11 rather than 3.12 (as that seems to not require building the qdldl wheel).
